name: a more complex workflow

on:
  push:
    branches:
      - jakobalander
  pull_request:
    branches:
      - master

jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        count: [1, 2, 3]
    steps:
      - name: Say hello
        env:
          GREETING: Hello nice people at
          COMPANY: Diabol
        run: |
          echo ${{ matrix.count }} $GREETING $COMPANY

  my_second_job:
    name: My Second Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v2

      - name: checkout another repo
        uses: actions/checkout@v2
        with:
          repository: jakobalander/dotfiles
          path: dotfiles

      - name: print the file structure
        run: |
          ls -la

  my_third_job:
    name: My Third Job
    runs-on: ubuntu-latest
    needs: [my_first_job, my_second_job]
    steps:
      - name: finally done
        run: |
          echo "finally done"
      - name: reveal a secret...
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}

